- name: Create auto scaling group with launch configuration
  hosts: localhost
  gather_facts: False
  vars:
    region: ap-south-1
    launch_config_name: my-launch-config
    auto_scaling_group_name: my-auto-scaling-group
    subnet_ids:
      - subnet-0437e8581e051b415
      - subnet-0ae75bd3af254e7c9
    security_group_ids:
      - sg-045efaad6b28db6e8
    image_id: ami-002070d43b0a4f171
    instance_type: t2.micro
    key_name: DevOps
    min_size: 1
    max_size: 1
    desired_capacity: 1
    health_check_type: EC2
    health_check_grace_period: 300
    tags:
      - key: Name
        value: my-auto-scaling-group
  tasks:
    - name: Create launch configuration
      ec2_lc:
        name: "{{ launch_config_name }}"
        image_id: "{{ image_id }}"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        security_groups: "{{ security_group_ids }}"
        region: "{{ region }}"
        user_data: |
          #!/bin/bash
          yum update -y
          amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
          yum install -y httpd mariadb-server
          systemctl start httpd
          systemctl enable httpd
          usermod -a -G apache ec2-user
          chown -R ec2-user:apache /var/www
          chmod 2775 /var/www
          find /var/www -type d -exec chmod 2775 {} \;
          find /var/www -type f -exec chmod 0664 {} \;
          yum install -y git
          sudo git clone https://github.com/sharonraju143/AWS-Project.git /var/www/html
      register: lc_result

    - name: Create auto scaling group
      ec2_asg:
        name: "{{ auto_scaling_group_name }}"
        launch_config_name: "{{ launch_config_name }}"
        min_size: "{{ min_size }}"
        max_size: "{{ max_size }}"
        desired_capacity: "{{ desired_capacity }}"
        region: "{{ region }}"
        vpc_zone_identifier: "{{ subnet_ids | join(',') }}"
        health_check_type: "{{ health_check_type }}"
        health_check_period: "{{ health_check_grace_period }}"
        tags: "{{ tags }}"
        state: present
      register: asg_result
