---
- name: Deploy .NET web application on Windows Server
  hosts: windows_servers
  gather_facts: no
  tasks:
  - name: Install IIS
    win_feature:
      name: Web-Server
      state: present
  - name: Copy web application files
    win_copy:
      src: s3://sourcecodedotnet/POC/
      dest: C:\inetpub\wwwroot\myapp
  - name: Create application pool
    win_iis_webapppool:
      name: myapppool
      state: present
      managed_pipeline_mode: Integrated
      managed_runtime_version: v4.0
  - name: Create website
    win_iis_website:
      name: mywebsite
      state: present
      physical_path: C:\inetpub\wwwroot\myapp
      application_pool: myapppool
      bindings:
      - protocol: http
        ip_address: "*"
        port: 80
  - name: Configure web application
    win_iis_webapplication:
      site: mywebsite
      name: myapp
      physical_path: C:\inetpub\wwwroot\myapp
      application_pool: myapppool
      state: present

