---
- name: Install IIS and other dependencies using Server Manager
  hosts: windows-server
  gather_facts: false
  become: yes

  tasks:
  - name: Install IIS and other dependencies
    win_feature:
      name:
        - Web-Server
        - NET-Framework-45-Core
        - Web-Asp-Net45
        - Web-Net-Ext45
        - WAS
      state: present
    register: feature_result

  - name: Reboot if needed
    win_reboot:
    when: feature_result.reboot_required

  - name: Wait for server to come back up
    wait_for_connection:
      delay: 30
      timeout: 300

